// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqqgXIv5JmLj4iCBWHzfcO1Jbnpf2nsU',
    appId: '1:978742575099:web:4f949d4de49e343e1f955e',
    messagingSenderId: '978742575099',
    projectId: 'zylu-employee-directory',
    authDomain: 'zylu-employee-directory.firebaseapp.com',
    storageBucket: 'zylu-employee-directory.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO5rilfNUsfgOFxj1yxcEknEVPm7SuTE4',
    appId: '1:978742575099:android:d0d62d20ce9083011f955e',
    messagingSenderId: '978742575099',
    projectId: 'zylu-employee-directory',
    storageBucket: 'zylu-employee-directory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6y3iyZp0fm5a_bKee--UFZ7yuzGaShc0',
    appId: '1:978742575099:ios:66245858029d38e01f955e',
    messagingSenderId: '978742575099',
    projectId: 'zylu-employee-directory',
    storageBucket: 'zylu-employee-directory.firebasestorage.app',
    iosClientId: '978742575099-rnmr2inrkv0bnlomj4kaij7bvve59ouj.apps.googleusercontent.com',
    iosBundleId: 'com.example.zylu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6y3iyZp0fm5a_bKee--UFZ7yuzGaShc0',
    appId: '1:978742575099:ios:66245858029d38e01f955e',
    messagingSenderId: '978742575099',
    projectId: 'zylu-employee-directory',
    storageBucket: 'zylu-employee-directory.firebasestorage.app',
    iosClientId: '978742575099-rnmr2inrkv0bnlomj4kaij7bvve59ouj.apps.googleusercontent.com',
    iosBundleId: 'com.example.zylu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIqqgXIv5JmLj4iCBWHzfcO1Jbnpf2nsU',
    appId: '1:978742575099:web:39c5122491dc70281f955e',
    messagingSenderId: '978742575099',
    projectId: 'zylu-employee-directory',
    authDomain: 'zylu-employee-directory.firebaseapp.com',
    storageBucket: 'zylu-employee-directory.firebasestorage.app',
  );
}
